(.venv) vikimulhall@Viki community % curl https://cli-assets.heroku.com/install.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1980  100  1980    0     0   6685      0 --:--:-- --:--:-- --:--:--  6875
This script requires superuser access.
You will be prompted for your password by sudo.
Password:
Installing CLI from https://cli-assets.heroku.com/channels/stable/heroku-darwin-arm64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 72.1M  100 72.1M    0     0  9849k      0  0:00:07  0:00:07 --:--:-- 11.4M
v20.17.0
heroku installed to /usr/local/bin/heroku
heroku/10.0.2 darwin-arm64 node-v20.17.0
(.venv) vikimulhall@Viki community % heroku login -i
heroku: Enter your login credentials
Email [vikimulhall@gmail.com]: vikimulhall@gmail.com
Password: ******
 ›   Error: Invalid credentials provided.
 ›
 ›   Error ID: unauthorized
(.venv) vikimulhall@Viki community % heroku login -i
heroku: Enter your login credentials
Email [vikimulhall@gmail.com]: vikimulhall@gmail.com
Password: **************
 ›   Error: Your account has MFA enabled; API requests using basic authentication with email and password are not supported. Please generate an 
 ›   authorization token for API access. 
 ›
 ›   Error ID: vaas_enrolled
(.venv) vikimulhall@Viki community % heroku login -i
heroku: Enter your login credentials
Email [vikimulhall@gmail.com]: vikimulhall@gmail.com
Password: *****************************************
Logged in as vikimulhall@gmail.com
(.venv) vikimulhall@Viki community % <200b><feff>heroku apps
zsh: command not found: \u200b\ufeffheroku
(.venv) vikimulhall@Viki community % heroku logs --tail --app community-noticeboard-app


2025-02-05T02:51:29.264189+00:00 app[web.1]: Traceback (most recent call last):
2025-02-05T02:51:29.264189+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/backends/postgresql/base.py", line 27, in <module>
2025-02-05T02:51:29.264199+00:00 app[web.1]: import psycopg2 as Database
2025-02-05T02:51:29.264200+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/psycopg2/__init__.py", line 51, in <module>
2025-02-05T02:51:29.264200+00:00 app[web.1]: from psycopg2._psycopg import (                     # noqa
2025-02-05T02:51:29.264200+00:00 app[web.1]: ...<10 lines>...
2025-02-05T02:51:29.264201+00:00 app[web.1]: )
2025-02-05T02:51:29.264201+00:00 app[web.1]: ImportError: /app/.heroku/python/lib/python3.13/site-packages/psycopg2/_psycopg.cpython-313-x86_64-linux-gnu.so: undefined symbol: _PyInterpreterState_Get
2025-02-05T02:51:29.264202+00:00 app[web.1]: 
2025-02-05T02:51:29.264202+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2025-02-05T02:51:29.264202+00:00 app[web.1]: 
2025-02-05T02:51:29.264202+00:00 app[web.1]: Traceback (most recent call last):
2025-02-05T02:51:29.264203+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2025-02-05T02:51:29.264203+00:00 app[web.1]: worker.init_process()
2025-02-05T02:51:29.264203+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~^^
2025-02-05T02:51:29.264204+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/workers/base.py", line 134, in init_process
2025-02-05T02:51:29.264204+00:00 app[web.1]: self.load_wsgi()
2025-02-05T02:51:29.264204+00:00 app[web.1]: ~~~~~~~~~~~~~~^^
2025-02-05T02:51:29.264204+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2025-02-05T02:51:29.264204+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2025-02-05T02:51:29.264204+00:00 app[web.1]: ~~~~~~~~~~~~~^^
2025-02-05T02:51:29.264205+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-02-05T02:51:29.264205+00:00 app[web.1]: self.callable = self.load()
2025-02-05T02:51:29.264205+00:00 app[web.1]: ~~~~~~~~~^^
2025-02-05T02:51:29.264205+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-02-05T02:51:29.264205+00:00 app[web.1]: return self.load_wsgiapp()
2025-02-05T02:51:29.264206+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^
2025-02-05T02:51:29.264206+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-02-05T02:51:29.264206+00:00 app[web.1]: return util.import_app(self.app_uri)
2025-02-05T02:51:29.264206+00:00 app[web.1]: ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2025-02-05T02:51:29.264206+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/util.py", line 359, in import_app
2025-02-05T02:51:29.264207+00:00 app[web.1]: mod = importlib.import_module(module)
2025-02-05T02:51:29.264207+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-02-05T02:51:29.264207+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2025-02-05T02:51:29.264207+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05T02:51:29.264208+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-02-05T02:51:29.264208+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-02-05T02:51:29.264209+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-02-05T02:51:29.264209+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-02-05T02:51:29.264209+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
2025-02-05T02:51:29.264209+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-02-05T02:51:29.264210+00:00 app[web.1]: File "/app/community_centre/wsgi.py", line 16, in <module>
2025-02-05T02:51:29.264210+00:00 app[web.1]: application = get_wsgi_application()
2025-02-05T02:51:29.264210+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-02-05T02:51:29.264210+00:00 app[web.1]: django.setup(set_prefix=False)
2025-02-05T02:51:29.264210+00:00 app[web.1]: ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-02-05T02:51:29.264211+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-02-05T02:51:29.264211+00:00 app[web.1]: apps.populate(settings.INSTALLED_APPS)
2025-02-05T02:51:29.264211+00:00 app[web.1]: ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05T02:51:29.264211+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/apps/registry.py", line 116, in populate
2025-02-05T02:51:29.264211+00:00 app[web.1]: app_config.import_models()
2025-02-05T02:51:29.264212+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-02-05T02:51:29.264212+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/apps/config.py", line 269, in import_models
2025-02-05T02:51:29.264212+00:00 app[web.1]: self.models_module = import_module(models_module_name)
2025-02-05T02:51:29.264212+00:00 app[web.1]: ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
2025-02-05T02:51:29.264212+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-02-05T02:51:29.264213+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2025-02-05T02:51:29.264213+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05T02:51:29.264213+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-02-05T02:51:29.264213+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-02-05T02:51:29.264214+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-02-05T02:51:29.264218+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-02-05T02:51:29.264219+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
2025-02-05T02:51:29.264219+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-02-05T02:51:29.264219+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/contrib/auth/models.py", line 3, in <module>
2025-02-05T02:51:29.264219+00:00 app[web.1]: from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
2025-02-05T02:51:29.264220+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/contrib/auth/base_user.py", line 57, in <module>
2025-02-05T02:51:29.264220+00:00 app[web.1]: class AbstractBaseUser(models.Model):
2025-02-05T02:51:29.264220+00:00 app[web.1]: ...<109 lines>...
2025-02-05T02:51:29.264221+00:00 app[web.1]: )
2025-02-05T02:51:29.264221+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/models/base.py", line 143, in __new__
2025-02-05T02:51:29.264221+00:00 app[web.1]: new_class.add_to_class("_meta", Options(meta, app_label))
2025-02-05T02:51:29.264221+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05T02:51:29.264222+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/models/base.py", line 371, in add_to_class
2025-02-05T02:51:29.264222+00:00 app[web.1]: value.contribute_to_class(cls, name)
2025-02-05T02:51:29.264222+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
2025-02-05T02:51:29.264222+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/models/options.py", line 243, in contribute_to_class
2025-02-05T02:51:29.264222+00:00 app[web.1]: self.db_table, connection.ops.max_name_length()
2025-02-05T02:51:29.264223+00:00 app[web.1]: ^^^^^^^^^^^^^^
2025-02-05T02:51:29.264223+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/utils/connection.py", line 15, in __getattr__
2025-02-05T02:51:29.264223+00:00 app[web.1]: return getattr(self._connections[self._alias], item)
2025-02-05T02:51:29.264223+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
2025-02-05T02:51:29.264224+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/utils/connection.py", line 62, in __getitem__
2025-02-05T02:51:29.264224+00:00 app[web.1]: conn = self.create_connection(alias)
2025-02-05T02:51:29.264229+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/utils.py", line 193, in create_connection
2025-02-05T02:51:29.264229+00:00 app[web.1]: backend = load_backend(db["ENGINE"])
2025-02-05T02:51:29.264229+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/utils.py", line 113, in load_backend
2025-02-05T02:51:29.264229+00:00 app[web.1]: return import_module("%s.base" % backend_name)
2025-02-05T02:51:29.264230+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-02-05T02:51:29.264230+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2025-02-05T02:51:29.264230+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-05T02:51:29.264230+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
2025-02-05T02:51:29.264230+00:00 app[web.1]: raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
2025-02-05T02:51:29.264231+00:00 app[web.1]: django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module
2025-02-05T02:51:29.264315+00:00 app[web.1]: [2025-02-05 02:51:29 +0000] [10] [INFO] Worker exiting (pid: 10)
2025-02-05T02:51:29.301898+00:00 app[web.1]: [2025-02-05 02:51:29 +0000] [2] [WARNING] Worker with pid 10 was terminated due to signal 15
2025-02-05T02:51:29.398722+00:00 app[web.1]: [2025-02-05 02:51:29 +0000] [2] [INFO] Shutting down: Master
2025-02-05T02:51:29.398744+00:00 app[web.1]: [2025-02-05 02:51:29 +0000] [2] [INFO] Reason: Worker failed to boot.
2025-02-05T02:51:29.458469+00:00 heroku[web.1]: Process exited with status 3
2025-02-05T02:51:29.481060+00:00 heroku[web.1]: State changed from starting to crashed
